Bug #927960 soc: sprd: debug: fix compile error
[root cause  ] types is not equal and lack cast
[changes     ] trace_eirqsoff.c
[side effects]no
[self test   ]:yes
[download normally]:yes
[power on/off normally]:yes
[do common repository/branch inspection]:yes
[is there dependence]:no
[confirm dependent commit]:yes
[board]:sharkl5-go
[test case]:sharkl5-go bringup
[reviewers   ] nianfu.bai
[change_type ] debug_log
[tag_product ] common

1. fix following error:
div64.h:208:28: error: comparison of distinct pointer types lacks a cast [-Werror]
  (void)(((typeof((n)) *)0) == ((uint64_t *)0)); \
                            ^
2. fix compiler error when PREEMPT_TRACER disable,

Signed-off-by: Janet Liu <janet.liu@spreadtrum.com>

Change-Id: Ifd27b088a1eaa2dff62e27749ad47b888f2d0da4