EKmoto_e40-4883:[STS11_2022-03]CtsSecurityBulletinHostTestCases fail
Description:
armeabi-v7a CtsSecurityBulletinHostTestCases
android.security.cts.CVE_2020_29368#testPocCVE_2020_29368 fail
java.lang.AssertionError: PoC returned exit status 113: vulnerable

Solution:
Kernel patch from Google.
https://partnerissuetracker.corp.google.com/issues/222152146
https://android.googlesource.com/kernel/common/+/407faed92b4a4e2ad900d61ea3831dd597640f29

St-result: PASS

Change-Id: Ie0340f505bde2dc15ba2bcf69cd0d7793ea214ed
(cherry picked from commit a3a2b481c21d015aaf878bf16c366f62431ac852)