Bug #1079807 sched: fix compiling error on `min_cap_cpu_mask`
[self test   ] lava
[change_type ] r&d

When compiling uml for kunit, we get this:

kernel/sched/core.o: In function `bitmap_copy':
/home/orson/code/k414-work/./include/linux/bitmap.h:215:
undefined reference to `min_cap_cpu_mask'

`min_cap_cpu_mask` is defined in enery.c which depends optional macro.
And we do not enable it this time.

From kernel/sched/Makfile
"obj-$(CONFIG_GENERIC_ARCH_TOPOLOGY) += energy.o"

Change-Id: I2b1d96c8ecfc2a87bd2f9e4affb3d32c3a7e4c1e
Signed-off-by: Orson Zhai <orson.zhai@spreadtrum.com>
Signed-off-by: Cixi.Geng <gengcx@spreadst.com>