Bug #524805 soc: sprd: debug: fix compile error on arm platform
[root cause  ] / not support on arm
[changes     ] trace_eirqsoff.c
[side effects] no
[self test   ]: yes
[download normally]:yes
[power on/off normally]:yes
[do common repository/branch inspection]: yes
[is there dependence]: no
[confirm dependent commit]:yes
[board]:sp9863a
[test case]:bringup
[reviewers   ] xiongxian.an
[change_type ] feature_bugfix
[tag_product ] common

for compile error on arm:
drivers/built-in.o: In function `stop_eirqsoff_timing':
kernel/drivers/soc/sprd/debug/eirqsoff/trace_eirqsoff.c:86:
    undefined reference to `__aeabi_ldivmod'

Change-Id: I72c923f3e1ab89fef45e2179673296dbb843c836
Signed-off-by: Janet Liu <janet.liu@spreadtrum.com>