Bug #1890034 unisoc_platform: fix gcc compile Werror=sizeof-pointer-memaccess
[root cause  ] gcc compile Werror
[changes     ] kernel
[side effects] no
[self test   ]: ikt
[download normally]: yes
[power on/off normally]: yes
[do common repository/branch inspection]: yes
[is there dependence]: no
[confirm dependent commit]: yes
[board]: sprd
[test case]: ikt-gcc_compile
[reviewers   ] Orson Zhai
[change_type ] bringup --> sprd_chip_support
[tag_product ] common

printk_cpuid.c:25:26: error: argument to ‘sizeof’ in ‘snprintf’
call is the same expression as the destination; did you mean
to provide an explicit length? [-Werror=sizeof-pointer-memaccess]
   25 |   snprintf(caller, sizeof(caller), "%c%u",

Change-Id: I0e35d24b8d3a176f4f0a39d806e134396af194b2
Signed-off-by: Cixi Geng <cixi.geng1@unisoc.com>