Bug #1271791 mm: memblock: fix build error with clang
[root cause  ] [-Werror,-Wconstant-conversion]
[changes     ] explicitly convert the type
[side effects] no
[self test   ]: yes
[download normally]: yes
[power on/off normally]: yes
[do common repository/branch inspection]: yes
[is there dependence]: no
[confirm dependent commit]: no
[board]: all
[test case]: build with clang
[reviewers   ] nianfu.bai
[change_type ] feature_bugfix
[tag_product ] common

Explicitly convert the type for errors with clang:
mm/memblock.c:937:15: error: implicit conversion from 'unsigned long
long' to 'phys_addr_t' (aka 'unsigned int') changes value from
18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
	r->base : ULLONG_MAX;
		  ^~~~~~~~~~
include/linux/kernel.h:30:21: note: expanded from macro 'ULLONG_MAX'
	#define ULLONG_MAX      (~0ULL)
				^~~~~
mm/memblock.c:1053:15: error: implicit conversion from 'unsigned long
long' to 'phys_addr_t' (aka 'unsigned int') changes value from
18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
	r->base : ULLONG_MAX;
		  ^~~~~~~~~~
include/linux/kernel.h:30:21: note: expanded from macro 'ULLONG_MAX'
	#define ULLONG_MAX      (~0ULL)
				^~~~~

Change-Id: I7838f109bc89d681445dbba2cd7b0d1ea07aa788
Signed-off-by: Candle Sun <candle.sun@unisoc.com>