Bug #1521638 soc: sprd: repair of casting error
[root cause  ] Cast error
[changes     ] Modify c code
[side effects] None
[self test   ]: Yes
[download normally]: Yes
[power on/off normally]: Yes
[do common repository/branch inspection]: Yes
[is there dependence]: No
[confirm dependent commit]: Yes
[board]: ums512_1h10, ums512_2h10
[test case]: Deep, Light, Wakeup, Power on/off
[reviewers   ] meixia.wang
[change_type ] bringup --> sprd_chip_support
[tag_product ] common

error: cast to smaller integer type 'int' from 'struct power_debug_cfg *'.

Change-Id: I162c1318ae7009ef2caa16ffb4de54b99c003552
Signed-off-by: DeVen Sheng <deven.sheng@spreadtrum.com>