Bug #912797 soc: sprd: dmc: change div method for 32bit arm
[root cause ] dmc change div method for 32bit arm
[changes ] dmc change div method for 32bit arm
[side effects] No
[self test ]: test ok
[download normally]: Yes
[power on/off normally]: Yes
[do common repository/branch inspection]: Yes
[is there dependence]: No
[confirm dependent commit]: No
[board]: sharle
[test case]: cat /sys/kernel/debug/sprd_pub_monitor/status
[reviewers ] junqiang.wang
[change_type ] feature
[tag_product ] specific

Fix following error in arm32 sharkl5:
space/builder/repo/common_build_3_26506/kernel4.14/drivers/soc/sprd/pub/dmc_drv.c:271: error: undefined reference to '__aeabi_uldivmod'
/space/builder/repo/common_build_3_26506/kernel4.14/drivers/soc/sprd/pub/dmc_drv.c:279: error: undefined reference to '__aeabi_uldivmod'
FAILED: out/target/product/ums510_2h10_go_32b/obj/KERNEL/arch/arm/boot/Image 

Change-Id: Id029d39b262831049d0ba52657cc00a9dc479e51
Singed-off-by: Sun Kui