Bug #2630180 unisoc_platform: fix the gcc build error
[root cause  ]: fix gcc build error
[changes     ]: drives code
[side effects]: null
[self test   ]: yes
[download normally]: yes
[power on/off normally]: yes
[do common repository/branch inspection]: yes
[is there dependence]: no
[confirm dependent commit]: yes
[board]: sprd
[test case]: ikt-gcc
[reviewers]: cixi.geng

commit_template_version:v1
fix build error:
error: format '%lu' expects argument of type 'long unsigned int'
but argument 3 has type 'uint32_t' {aka 'unsigned int'}
[-Werror=format=]

Change-Id: I8af49bd91cea4b8a57a4b92ae27de60fa5ec7898
Signed-off-by: Cixi Geng <cixi.geng1@unisoc.com>