ANDROID: GKI: add mem_section to pixel's symbol list
We switched to the generic version of pfn_valid() after backporting
upstream commit 3de360c3fdb3 ("arm64/mm: drop HAVE_ARCH_PFN_VALID").
However, the generic version uses mem_section array which needs to be
added to the symbol list.

This fixes the following build error:
ERROR: modpost: "mem_section" [../gs/google-modules/soc-modules/drivers/iommu/samsung_iommu.ko] undefined!

Generated via:
$ KMI_SYMBOL_LIST_STRICT_MODE=0 TRIM_NONLISTED_KMI=0 ./build_slider.sh
$ build/abi/extract_symbols \
  --additions-only --skip-module-grouping --symbol-list \
  common/android/abi_gki_aarch64_pixel out/android13-5.15/dist

Bug: 231461582
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I49bf4211d3fd8b3c0de17ed6e194e5a8f63a27f5