Bug #1535689 soc: sprd: repair of casting error
[root cause  ] Cast error
[changes     ] Modify c code
[side effects] None
[self test   ]: Yes
[download normally]: Yes
[power on/off normally]: Yes
[do common repository/branch inspection]: Yes
[is there dependence]: No
[confirm dependent commit]: Yes
[board]: sharkl3
[test case]: Deep, Light, Wakeup, Power on/off
[reviewers   ] jignchao.ye, meixia.wang
[change_type ] bringup --> sprd_chip_support
[tag_product ] common

error: cast to smaller integer type 'int' from 'struct power_debug_cfg *'.

Change-Id: Ibb3a83d53abab49f80673fc8f0755583228e0436
Signed-off-by: Qinjiang Ye <qinjiang.ye@unisoc.com>