ANDROID: Fix kernelci build break due to typo
Fix a typo that results in build error:

drivers/irqchip/irq-gic.c:1266:2: error: implicit declaration of function 'gic_v2_syscore_init'

Fixes: 61b67cda3498 ("ANDROID: irqchip: irq-gic: Add vendor hook for gic-v2 resume")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: I48c677c2f167dbdb49db6debbc41966cfcb79b3e