Bug #1254865 include: uapi: add sprd_jpg header file to kernel5.4
[root cause  ] compile error, lack header file sprd_jpg.h
[changes     ] copy the header file from kernel4.14
[side effects] none
[self test   ]:compile pass
[download normally]:yes
[power on/off normally]:yes
[do common repository/branch inspection]:yes
[is there dependence]:no
[confirm dependent commit]:yes
[board]:9863a
[test case]:compile
[reviewers   ] Orson Zhai
[change_type ] bringup --> sprd_chip_support
[tag_product ] common

Add header file to make the build of userspace library successful.

(Fix: CONFIG_UAPI_HEADER_TEST was set at GKI build. There are couple
of errors reported by this.)

We got follwing error triggerrd after kernel upgrade:

> error: include/uapi/video/sprd_jpg.h: leak CONFIG_COMPAT to user-space
> scripts/Makefile.headersinst:63: recipe for target 'usr/include/video/sprd_jpg.h' failed
> make[1]: *** [usr/include/video/sprd_jpg.h] Error 1
> Makefile:1270: recipe for target 'headers' failed

CONFIG_COMPAT is useless at userland, thus the code in its effective
range will be never usable for user application.

Add __KERNEL__ macro to avoid it to be leaked.

Change-Id: I8c40cc306d35727cb30c638738dff09570ebfeeb
Signed-off-by: Leon Li <leon.li@unisoc.com>
Signed-off-by: Orson Zhai <orson.zhai@unisoc.com>