Bug #1298108 REVERT: "Bug #1298108 serial: sprd: add cm4 uart driver"
This reverts commit ec269b620c07703c9dab0350313a87b7c879a2f5.
which breaks aiaiai.

 Failed to build the base commit: f79b111 Bug #1300150 arch: arm64: sharkl5 camera bringup
 Configuration: "sprd_minimum_defconfig, architecture arm64".
 
 
 scripts/dtc/dtc.c: In function 鈥榤ain鈥�:
 scripts/dtc/dtc.c:274: warning: implicit declaration of function 鈥榙tbo_merge_chk_main鈥�
 scripts/dtc/libfdt/dtbo_merge_check.c:8: warning: no previous prototype for 鈥榙tbo_merge_chk_main鈥�
 drivers/tty/serial/sprd_serial_ex.o: In function `sprd_remove':
 sprd_serial_ex.c:(.text+0x5e4): undefined reference to `sbuf_destroy'
 sprd_serial_ex.c:(.text+0x5e4): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `sbuf_destroy'
 drivers/tty/serial/sprd_serial_ex.o: In function `sprd_probe':
 sprd_serial_ex.c:(.text+0xae4): undefined reference to `sbuf_create_ex'
 sprd_serial_ex.c:(.text+0xae4): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `sbuf_create_ex'
 sprd_serial_ex.c:(.text+0xb08): undefined reference to `sbuf_register_notifier'
 sprd_serial_ex.c:(.text+0xb08): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `sbuf_register_notifier'
 drivers/tty/serial/sprd_serial_ex.o: In function `sprd_cm4_uart_tx':
 sprd_serial_ex.c:(.text+0xe24): undefined reference to `sbuf_write'
 sprd_serial_ex.c:(.text+0xe24): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `sbuf_write'
 sprd_serial_ex.c:(.text+0xe94): undefined reference to `sbuf_write'
 sprd_serial_ex.c:(.text+0xe94): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `sbuf_write'
 drivers/tty/serial/sprd_serial_ex.o: In function `sprd_cm4_uart_rx':
 sprd_serial_ex.c:(.text+0xf1c): undefined reference to `sbuf_read'
 sprd_serial_ex.c:(.text+0xf1c): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `sbuf_read'
 make[2]: *** [vmlinux] Error 1

Change-Id: Ibf552e88d80b19b531e6fd3a67a088b5d6093073
Signed-off-by: Orson Zhai <orson.zhai@unisoc.com>