Bug #1024495 cpufreq: sprd: avoid compilation risk
[root cause  ] Resolve dvfs driver compilation error
[changes     ] cpufreq
[side effects] no
[self test   ]: yes
[download normally]: yes
[power on/off normally]: yes
[do common repository/branch inspection]: no
[is there dependence]: no
[confirm dependent commit]: no
[board]:ums518-haps
[test case]:dvfs test,sleep wakeup
[reviewers   ]
[change_type ] bringup --> sprd_chip_support
[tag_product ] specific

This patch resolve sharkl5pro haps dvfs driver compilation error

when CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y, there is build error as
below:
error: 'tbl' may be used uninitialized 
in this function [-Werror=maybe-uninitialized]
error: 'dcdc_group_array' may be used uninitialized
in this function [-Werror=maybe-uninitialized]

Change-Id: I7c170bbab1e5c9a71e23ce8d49f001546a3d91fc
Signed-off-by: yongye.chen <yongye.chen@unisoc.com>