FROMLIST: genirq: Export irq_check_status_bit
Changing some inline functions to use the new irq_check_status_bit
function out of line breaks calling them from loadable modules:

ERROR: modpost: "irq_check_status_bit" [drivers/perf/arm_spe_pmu.ko] undefined!

Export the function to make it work again. One can debate over
whether this should be EXPORT_SYMBOL() or EXPORT_SYMBOL_GPL(),
as it could be called from any module before and making it GPL-only
changes behavior. However all other symbols in this file are
EXPORT_SYMBOL_GPL(), so I went with that for consistency.

Fixes: fdd029630434 ("genirq: Move status flag checks to core")
Link: https://lore.kernel.org/r/20201230154600.697832-1-arnd@kernel.org
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>
Change-Id: I4bc338352263445a2e3421e5116ead1c69c90768