Bug #1244212 soc: sprd: debug: fixed compiling error
[root cause  ] gcc enable "-Werror,-Wshift-count-overflow"
[changes     ] sprd_last_regs.c
[side effects]no
[self test   ]:yes
[download normally]:yes
[power on/off normally]:yes
[do common repository/branch inspection]:yes
[is there dependence]:no
[confirm dependent commit]:yes
[board]:sp9863a
[test case]:build&bringup
[reviewers   ] chunyang.zhang enlai.chu
[change_type ] feature_bugfix
[tag_product ] common

fixed following compiling error:
kernel4.14/drivers/soc/sprd/debug/last_regs/sprd_last_regs.c:42:34:
    error: shift count >= width of type [-Werror,-Wshift-count-overflow]
static u64 sprd_debug_dma_mask = DMA_BIT_MASK(sizeof(long)<<3);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kernel4.14/include/linux/dma-mapping.h:140:54: note: expanded from macro 'DMA_BIT_MASK'
                                                     ^ ~~~
kernel4.14/drivers/soc/sprd/debug/last_regs/sprd_last_regs.c:45:28:
    error: shift count >= width of type [-Werror,-Wshift-count-overflow]

Signed-off-by: Janet Liu <janet.liu@spreadtrum.com>
Change-Id: Ifcdc5e3869947907a28d1cbcb6a171284472b4f9