Bug #1066878 soc: sprd: iommu: removes code build warnings for clang
[root cause  ] [-Werror,-Wenum-conversion]
[changes     ] Explicitly converts the type
[side effects] No
[self test   ]: Yes
[download normally]: Yes
[power on/off normally]: Yes
[do common repository/branch inspection]: Yes
[is there dependence]: No
[confirm dependent commit]: No
[board]: sp9863a
[test case]: build by clang
[reviewers   ] nianfu.bai
[change_type ] feature
[tag_product ] common

Explicitly convert the type for clang error:
drivers/soc/sprd/iommu/drv/sprd_iommuex_ops.c:171:36:
error: implicit conversion from enumeration type 'enum sprd_iommu_chtype'
to different enumeration type 'enum sprd_iommu_ch_type
[-Werror,-Wenum-conversion]
        map_param.channel_type = p_param->ch_type;
                               ~ ~~~~~~~~~^~~~~~~

Change-Id: Idc2710c72fe0b9793db02fc0bcc714b296bbb481
Signed-off-by: Candle Sun <candle.sun@unisoc.com>