Bug #1005477 cpufreq: open feature to export CPU time-in-state information through procfs
[root cause  ] not open the feature export CPU time-in-state information
[changes     ] open the feature export to CPU time-in-state information
[side effects]no
[self test   ]:yes
[download normally]:yes
[power on/off normally]:yes
[do common repository/branch inspection]:yes
[is there dependence]:no
[confirm dependent commit]:yes
[board]:sharkl5
[test case]:check procfs node
[reviewers   ]
[change_type ] feature_bugfix
[tag_product ] common

fix follow error:
KernelUidCpuFreqTimeReader: Failed to read /proc/uid_time_in_state:
java.io.FileNotFoundException: /proc/uid_time_in_state (No such file or directory)

Change-Id: I9c0680f2e8574f8765a2f0dc8302338867650f71
Signed-off-by: Samer Xie <samer.xie@unisoc.com>