Bug #2120771 scripts: unisoc: fix the log not correct arch info
[root cause  ]: the ARCH always is arm64.it should be arch
[changes     ]: scripts
[side effects]: no
[self test   ]: yes
[download normally]: yes
[power on/off normally]: yes
[do common repository/branch inspection]: yes
[is there dependence]: no
[confirm dependent commit]: yes
[board]: sprd
[test case]: build
[reviewers]: cixi.geng

commit_template_version:v1
[change_type ] bringup --> sprd_chip_support
[tag_product ] common

when defconfig check fail, the log as follow:
ERROR: savedefconfig does not match
kernel5.15/arch/arm64/configs/sprd_defconfig
sprd_defconfig is for arm, and gki_defconfig is for arm64.
fix the print log

Change-Id: I2ce667b58544009c15129b1a64cf0330e87a1c8b
Signed-off-by: Cixi Geng <cixi.geng1@unisoc.com>