Bug #1087256 cpufreq: sprd: Solve compile error when open the marco CONFIG_CC_OPTIMZE_FOR_PERFORMANCE
[root cause  ] The variables have not been initialized
[changes     ] Initialize the variables when open the marco CONFIG_CC_OPTIMZE_FOR_PERFORMANCE
[side effects] no
[self test   ]: dvfs test
[download normally]:yes
[power on/off normally]:yes
[do common repository/branch inspection]:no
[is there dependence]:no
[confirm dependent commit]:no
[board]:ums312_1h10
[test case]:dvfs test,reboot test,sleep wakeup
[reviewers   ] jack.liu ling_ling.xu jingchao.ye sheng.zhu
[change_type ] bringup --> sprd_adaptation
[tag_product ] common

When open the marco CONFIG_CC_OPTIMZE_FOR_PERFORMANCE, but variables have not been
initialized, the compile error as follows will occur.

/home/builder/hudsonagent164/workspace/8x/repo/kernel4.14/drivers/cpufreq/sprd-hwdvfs-normal.c: In function
'sprd_cpudvfs_udelay_update':
/home/builder/hudsonagent164/workspace/8x/repo/kernel4.14/drivers/cpufreq/sprd-hwdvfs-normal.c:1400:28: error:
'max_j' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 max_j, max_i, max_j, vol[max_j], max_i, vol[max_i], max_diff);

Change-Id: Ic4cf948198e41c650e1a934178685b0b4ca2479e
Signed-off-by: Jack Liu <jack.liu@spreadtrum.com>