Bug #1907237 arm64: configs: enable trusty configs in debian
[root cause  ]: the disp driver depense on the trusty
[changes     ]: configs
[side effects]: compile fail
[self test   ]:IKT
[download normally]: yes
[power on/off normally]: yes
[do common repository/branch inspection]: yes
[is there dependence]: yes
[confirm dependent commit]: yes
[board]: sprd
[test case]: build
[reviewers]:cixi.geng1
[change_type ] bringup --> sprd_chip_support
[tag_product ] common

aarch64-linux-gnu-ld: Unexpected GOT/PLT entries detected!
aarch64-linux-gnu-ld: Unexpected run-time procedure linkages detected!
drivers/unisoc_platform/sprd_disp/dpu/dpu_r4p0.o: in function `dpu_fini':
kernel5.15/drivers/unisoc_platform/sprd_disp/dpu/dpu_r4p0.c:861:
undefined reference to `trusty_fast_call32'
drivers/unisoc_platform/sprd_disp/dpu/dpu_r4p0.o: in function `dpu_init':
kernel5.15/drivers/unisoc_platform/sprd_disp/dpu/dpu_r4p0.c:847:
undefined reference to `trusty_fast_call32'

Change-Id: I35c50831214c38bdaa16def2750eb6f832f69cc6
Signed-off-by: Cixi Geng <cixi.geng1@unisoc.com>